development:
  adapter: postgresql
  encoding: utf-8
  database: leadershares2_development
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  encoding: utf-8
  database: leadershares2_test
  pool: 5
  timeout: 5000

cucumber:
  <<: *test